[package]
name = "svg2img"
version = "0.1.0"
edition = "2021"
authors = ["Orvar Segerström <orvarsegerstrom@gmail.com>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.6.2" }
